import enum


class GridValueContext(str, enum.Enum):
    GENERIC = "GENERIC"
    PROPERTY = "PROPERTY"
    CONFIGURATION = "CONFIGURATION"
    MEASUREMENT = "MEASUREMENT"
    ESTIMATION = "ESTIMATION"
