import enum


class MMSFunctionalConstraints(str, enum.Enum):
    NONE = "NONE"

    PROCESS_VALUE_STATUS_ST = "ST"
    PROCESS_VALUE_MEASURAND_MX = "MX"
    PROCESS_COMMAND_BINARY_CO = "CO"
    PROCESS_COMMAND_ANALOG_SP = "SP"
    OPERATE_RECEIVED_OR = "OR"
    CONFIGURATION_CF = "CF"
    DESCRIPTION_DC = "DC"
    SETTINGS_GROUP_ACTIVE_SG = "SG"
    SETTINGS_GROUP_EDITABLE_SE = "SE"
